# Generated by Django 5.2.6 on 2025-10-10 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0014_alter_application_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ControlJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_slot_name', models.TextField(blank=True, max_length=200, null=True, verbose_name='Модели ИА')),
                ('act_number', models.IntegerField(blank=True, null=True, verbose_name='Номер акта ТО')),
                ('act_date', models.DateField(blank=True, null=True, verbose_name='Дата утверждения акта ТО')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_journal', to='application.application')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_journal', to='distribution.worker', verbose_name='Исполнитель')),
            ],
        ),
    ]
