# Generated by Django 5.2.6 on 2025-10-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controljournal',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Место проведения ТО'),
        ),
    ]
