# Generated by Django 5.2.6 on 2025-10-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_controljournal_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controljournal',
            name='act_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер акта ТО'),
        ),
    ]
