# Generated by Django 5.2.6 on 2025-10-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_alter_controljournal_act_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='controljournal',
            name='notice',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='controljournal',
            name='act_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата утверждения акта ТО'),
        ),
    ]
