# Generated by Django 5.2.6 on 2025-10-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_controljournal_notice_alter_controljournal_act_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controljournal',
            name='act_date',
        ),
        migrations.AddField(
            model_name='controljournal',
            name='act',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Дата утверждения акта ТО'),
        ),
    ]
