# Generated by Django 5.2.6 on 2025-10-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_remove_controljournal_act_date_controljournal_act'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controljournal',
            name='act_number',
        ),
    ]
