# Generated by Django 5.2.6 on 2025-10-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0006_remove_controljournal_act_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controljournal',
            name='act',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Акт ТО'),
        ),
    ]
