# Generated by Django 5.2.7 on 2025-10-28 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0008_controljournal_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controljournal',
            name='worker',
        ),
        migrations.AlterField(
            model_name='controljournal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
