# Generated by Django 5.2.6 on 2025-09-22 07:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declarant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('unp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('application_number_belgiss', models.IntegerField()),
                ('date_belgiss', models.DateTimeField(default=datetime.datetime)),
                ('num_of_mach', models.IntegerField()),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='application.declarant')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='application.status')),
            ],
        ),
    ]
