# Generated by Django 5.2.6 on 2025-09-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_belgiss',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
