# Generated by Django 5.2.6 on 2025-09-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_date_belgiss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_belgiss',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
