# Generated by Django 5.2.6 on 2025-09-22 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_application_date_belgiss'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bill_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='bill_number',
            field=models.CharField(default='DEFAULT_VALUE', max_length=20),
        ),
    ]
