# Generated by Django 5.2.6 on 2025-09-22 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_application_bill_date_application_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='bill_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_belgiss',
            field=models.DateField(blank=True, null=True),
        ),
    ]
