# Generated by Django 5.2.6 on 2025-09-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_application_bill_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='bill_number',
            field=models.CharField(default='115XXX/372', max_length=20),
        ),
    ]
