# Generated by Django 5.2.6 on 2025-09-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_application_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_number_belgiss',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
