# Generated by Django 5.2.6 on 2025-09-29 19:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_application_application_number_belgiss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_number_belgiss',
            field=models.IntegerField(blank=True, null=True, verbose_name='Входящий номер БелГИСС'),
        ),
        migrations.AlterField(
            model_name='application',
            name='bill_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата счета'),
        ),
        migrations.AlterField(
            model_name='application',
            name='bill_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_belgiss',
            field=models.DateField(blank=True, null=True, verbose_name='Дата входящего номера БелГИСС'),
        ),
        migrations.AlterField(
            model_name='application',
            name='declarant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='application.declarant', verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='application',
            name='num_of_mach',
            field=models.IntegerField(verbose_name='Количество ИА'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='application.status', verbose_name='Статус'),
        ),
    ]
