# Generated by Django 5.2.6 on 2025-09-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_application_application_number_belgiss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='bill_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата счета'),
        ),
    ]
