# Generated by Django 5.2.6 on 2025-09-30 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_application_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='application.status'),
        ),
        migrations.AlterField(
            model_name='declarant',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='declarant',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование заявителя'),
        ),
        migrations.AlterField(
            model_name='declarant',
            name='unp',
            field=models.IntegerField(verbose_name='УНП'),
        ),
    ]
