# Generated by Django 5.2.6 on 2025-10-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_application_status_alter_declarant_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pdf',
            field=models.FileField(default=1, upload_to='PDF/', verbose_name='PDF'),
            preserve_default=False,
        ),
    ]
