# Generated by Django 5.2.6 on 2025-10-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_application_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declarant',
            name='address',
            field=models.TextField(max_length=500, verbose_name='Юридический адрес'),
        ),
    ]
