# Generated by Django 5.2.6 on 2025-10-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_declarant_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='PDF/', verbose_name='PDF'),
        ),
    ]
