# Generated by Django 5.2.6 on 2025-10-24 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0007_alter_controljournal_act'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conformity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StickPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stick_place', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registry', to='act_creation.manufacturer', verbose_name='Изготовитель')),
            ],
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.IntegerField()),
                ('control_sticks_number', models.CharField(max_length=100)),
                ('slot_number', models.CharField(max_length=100)),
                ('board_number', models.CharField(max_length=50)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_to', to='distribution.controljournal')),
                ('conformity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='act_creation.conformity')),
                ('model_registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='act_creation.registry')),
            ],
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='stick_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='act_creation.stickplace'),
        ),
    ]
