# Generated by Django 5.2.6 on 2025-10-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_creation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickplace',
            name='board_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
