# Generated by Django 5.2.7 on 2025-10-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_creation', '0002_stickplace_board_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='manufacturer',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
