# Generated by Django 5.2.7 on 2025-10-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_creation', '0003_alter_registry_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='model',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registry',
            name='version',
            field=models.CharField(max_length=200),
        ),
    ]
