# Generated by Django 5.2.7 on 2025-10-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_creation', '0004_alter_registry_model_alter_registry_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='control_sticks_number',
            field=models.TextField(max_length=500),
        ),
    ]
