# Generated by Django 5.2.7 on 2025-10-30 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_creation', '0005_alter_act_control_sticks_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='№ Акта'),
        ),
        migrations.AlterField(
            model_name='act',
            name='board_number',
            field=models.CharField(max_length=50, verbose_name='Номер платы'),
        ),
        migrations.AlterField(
            model_name='act',
            name='conformity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='act_creation.conformity', verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='act',
            name='control_sticks_number',
            field=models.TextField(max_length=500, verbose_name='Номера средств контроля'),
        ),
        migrations.AlterField(
            model_name='act',
            name='model_registry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='act_creation.registry', verbose_name='Номер по реестру'),
        ),
        migrations.AlterField(
            model_name='act',
            name='slot_number',
            field=models.CharField(max_length=100, verbose_name='Серийный номер ИА'),
        ),
    ]
