# Generated by Django 5.2.7 on 2025-10-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_creation', '0006_alter_act_act_number_alter_act_board_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='control_sticks_number',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Номера средств контроля'),
        ),
    ]
